name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run tsc
      - run: npm run apps:web:tsc
      - run: npm testcov
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage-final.json
